
package com.mobile.data.usage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MobileDataUsageIntf", targetNamespace = "http://usage.data.mobile.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MobileDataUsageIntf {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMobileData", targetNamespace = "http://usage.data.mobile.com/", className = "com.mobile.data.usage.GetMobileData")
    @ResponseWrapper(localName = "getMobileDataResponse", targetNamespace = "http://usage.data.mobile.com/", className = "com.mobile.data.usage.GetMobileDataResponse")
    @Action(input = "http://usage.data.mobile.com/MobileDataUsageIntf/getMobileDataRequest", output = "http://usage.data.mobile.com/MobileDataUsageIntf/getMobileDataResponse")
    public String getMobileData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
