
package com.mobile.data.usage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MobileDataUsageImplService", targetNamespace = "http://usage.data.mobile.com/", wsdlLocation = "http://localhost:8080/WS/MobileDataUsageIntf?wsdl")
public class MobileDataUsageImplService
    extends Service
{

    private final static URL MOBILEDATAUSAGEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MOBILEDATAUSAGEIMPLSERVICE_EXCEPTION;
    private final static QName MOBILEDATAUSAGEIMPLSERVICE_QNAME = new QName("http://usage.data.mobile.com/", "MobileDataUsageImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/MobileDataUsageIntf?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOBILEDATAUSAGEIMPLSERVICE_WSDL_LOCATION = url;
        MOBILEDATAUSAGEIMPLSERVICE_EXCEPTION = e;
    }

    public MobileDataUsageImplService() {
        super(__getWsdlLocation(), MOBILEDATAUSAGEIMPLSERVICE_QNAME);
    }

    public MobileDataUsageImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOBILEDATAUSAGEIMPLSERVICE_QNAME, features);
    }

    public MobileDataUsageImplService(URL wsdlLocation) {
        super(wsdlLocation, MOBILEDATAUSAGEIMPLSERVICE_QNAME);
    }

    public MobileDataUsageImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOBILEDATAUSAGEIMPLSERVICE_QNAME, features);
    }

    public MobileDataUsageImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MobileDataUsageImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MobileDataUsageIntf
     */
    @WebEndpoint(name = "MobileDataUsageImplPort")
    public MobileDataUsageIntf getMobileDataUsageImplPort() {
        return super.getPort(new QName("http://usage.data.mobile.com/", "MobileDataUsageImplPort"), MobileDataUsageIntf.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileDataUsageIntf
     */
    @WebEndpoint(name = "MobileDataUsageImplPort")
    public MobileDataUsageIntf getMobileDataUsageImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://usage.data.mobile.com/", "MobileDataUsageImplPort"), MobileDataUsageIntf.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOBILEDATAUSAGEIMPLSERVICE_EXCEPTION!= null) {
            throw MOBILEDATAUSAGEIMPLSERVICE_EXCEPTION;
        }
        return MOBILEDATAUSAGEIMPLSERVICE_WSDL_LOCATION;
    }

}
